### Create user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email": "mehdi@gmail.com",
    "password": "mhd123"
}

### Login User
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email": "mehdi@gmail.com",
    "password": "mhd123"
}

### Find all Users 
GET http://localhost:3000/auth/

### Find a User with an ID
GET http://localhost:3000/auth/1

### Find all users with an email
GET http://localhost:3000/auth?email:aga@gmail.com

### Remove User by ID
DELETE http://localhost:3000/auth/1

### Update User by ID
PATCH http://localhost:3000/auth/1

### Set color in session
GET http://localhost:3000/auth/colors/blue

### Get color session
GET http://localhost:3000/auth/colors